--see how many customers are in our table:
select count(*) as "Customer Count" from customers;

--how many unique companies are in our table?
select count(distinct company)as "Distinct Companies" from customers ;

--add a column for the CompanyID to the customers table
alter table customers add CompanyID int;

--notice that the companyId is null
select companyID, company from customers;

--create a table for the companies
--this statement will also create a companyID column which will
--increment when you insert a new record
create table Company (
companyID number generated by default on null as identity,
Company varchar(50)
);

--see what's in your companies table now
select * from Companies;

--add a test company to verify that the identity field works
insert into companies(Company)values ('Dave Company');

--add unique companies from customers to the company table
insert into Companies (Company) select distinct company from customers;

--look at what you've done
select * from Companies;
--another way to select is to list the fields
select companyID, Company from customers;

--update the compnayId in the customers table
update customers c set c.companyID = (select t.companyID from
Companies t where t.company=c.company);

--query to check your data
select c.companyID,c.company,t.companyID,t.Company from
customers c inner join Companies t on c.CompanyID=t.CompanyID;

--remove the company column from the customers table. It is no longer needed.
alter table customers drop column company;

--notice you won't see the company column
select * from customers;
